import { useState } from "react";

const Rules = () => {
    const [open, setOpen] = useState<boolean>(false);

    const rules_pdf = "https://www.catan.com/sites/default/files/2021-06/catan_base_rules_2020_200707.pdf";

    function toggleHide() {
        let rules: HTMLDivElement = document.querySelector(`.rules__overlay`);
        rules.style.display = open ? "none" : "flex";
        setOpen(!open);
    }

    return (
        <>
            <div className="rules__button" onClick={toggleHide}>
                <i className="fa-solid fa-book">
                    <span className="tooltip">Rules</span>
                </i>
            </div>
            <div
                className="overlay rules__overlay"
                onClick={toggleHide}
                style={{ display: "none" }}
            >
                <div className="rules">
                    <h1>
                        <i className="fa-solid fa-book"></i>
                        Rules
                    </h1>

                    <section>
                        <h2>
                            <i className="fa-solid fa-flag"></i>
                            Objective
                        </h2>
                        <p>
                            Be the first to reach 10 Victory Points.
                            There are 5 ways to earn Victory Points:
                        </p>
                        <ol>
                            <li>Settlements are worth 1 point</li>
                            <li>Cities are worth 1 points</li>
                            <li>Longest Road is worth 2 points</li>
                            <li>Largest Army is worth 2 points</li>
                            <li>Victory Point cards are worth 1 point</li>
                        </ol>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-gamepad"></i>
                            Starting a Game
                        </h2>
                        <p>
                            <strong>!!! DO NOT</strong> disconnect or refresh the page.
                            There is no way to rejoin the room after disconnecting.
                        </p>
                        <p>
                            Click "Create Room" to create a room. Share the generated ID
                            with the other players.
                            Click "Join Room" button to join a room with an existing ID.
                            Once all players have joined, the host can then start the game.
                        </p>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-arrows-rotate"></i>
                            Taking a Turn
                        </h2>
                        <p>
                            During your turn, you will roll a dice for resource production.
                        </p>
                        <p>
                            Afterwards, you can choose to build infrastructure,
                            buy a development card, or conduct trade.
                        </p>
                        <p>
                            Remember to end your turn by clicking the check mark button.
                        </p>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-money-bill-wheat"></i>
                            Resources
                        </h2>
                        <p>
                            Resources are needed to build infrastructure and buy development cards.
                            They are generated by the tiles of their corresponding colours.

                            The sand colour tile is the desert, and is the only tile that does not
                            produce any resources.
                        </p>
                        <p>
                            There are 5 types of resources:
                        </p>
                        <ul>
                            <li>
                                <i
                                    className="fa-solid fa-trowel-bricks"
                                    style={{ color: "#f4b183" }}
                                ></i>
                                Brick
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-wheat-awn"
                                    style={{ color: "#ffd966" }}
                                ></i>
                                Grain
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-tree"
                                    style={{ color: "#70ad47" }}
                                ></i>
                                Lumber
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-mountain"
                                    style={{ color: "#c9c9c9" }}
                                ></i>
                                Ore
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-cloud"
                                    style={{ color: "#a9d18e" }}
                                ></i>
                                Wool
                            </li>
                        </ul>
                        <p>

                        </p>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-building-columns"></i>
                            Infrastructure
                        </h2>
                        <p>
                            You can build infrastructure by clicking on a path or intersection.
                            Infrastructure can only be built during your turn after rolling the dice.
                        </p>
                        <p>
                            Each infrastructure type has a maximum quota that can be built.
                            Each player can build 15 roads, 5 settlements and 4 cities in total.
                        </p>

                        <h3>
                            <i className="fa-solid fa-road"></i>
                            Roads
                        </h3>
                        <p>
                            Roads must be connected to one of your other roads, settlements or cities.
                        </p>
                        <p>
                            If you are the first player to build a continuous road with a length of 5,
                            you will earn the Longest Road card.

                            If another player builds a longer road, they will take the
                            Longest Road card.
                        </p>
                        <p>
                            Cost:
                        </p>
                        <ul>
                            <li>
                                <i
                                    className="fa-solid fa-trowel-bricks"
                                    style={{ color: "#f4b183" }}
                                ></i>
                                1 brick
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-tree"
                                    style={{ color: "#70ad47" }}
                                ></i>
                                1 lumber
                            </li>
                        </ul>

                        <h3>
                            <i className="fa-solid fa-oil-well"></i>
                            Settlements
                        </h3>
                        <p>
                            Settlements must be connected to one of your roads.
                            Settlements can only be built on intersections when all of its
                            adjacent intersections are unoccupied.
                        </p>
                        <p>
                            When the number of an adjacent tile is rolled, the owner of the
                            settlement will generate 1 resource of the associated type.
                        </p>
                        <p>
                            Cost:
                        </p>
                        <ul>
                            <li>
                                <i
                                    className="fa-solid fa-trowel-bricks"
                                    style={{ color: "#f4b183" }}
                                ></i>
                                1 brick
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-tree"
                                    style={{ color: "#70ad47" }}
                                ></i>
                                1 lumber
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-wheat-awn"
                                    style={{ color: "#ffd966" }}
                                ></i>
                                1 grain
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-cloud"
                                    style={{ color: "#a9d18e" }}
                                ></i>
                                1 wool
                            </li>
                        </ul>

                        <h3>
                            <i className="fa-solid fa-city"></i>
                            Cities
                        </h3>
                        <p>
                            Cities must be connected to one of your roads.
                            Cities can only be built on top of one of your settlements.
                        </p>
                        <p>
                            Cities generate double the resource production of settlements.
                        </p>
                        <p>
                            Cost:
                        </p>
                        <ul>
                            <li>
                                <i
                                    className="fa-solid fa-wheat-awn"
                                    style={{ color: "#ffd966" }}
                                ></i>
                                2 grain
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-mountain"
                                    style={{ color: "#c9c9c9" }}
                                ></i>v
                                3 ore
                            </li>
                        </ul>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-gamepad"></i>
                            Development Cards
                        </h2>
                        <p>
                            There are 5 types of Development Cards, each with its own effects.
                            Development cards are non-renewable and limited in quantity.
                            There are 14 knight cards, 2 road building cards, 2 year of plenty cards,
                            2 monopooly cards and 5 victory point cards.
                        </p>
                        <p>
                            Cost:
                        </p>
                        <ul>
                            <li>
                                <i
                                    className="fa-solid fa-wheat-awn"
                                    style={{ color: "#ffd966" }}
                                ></i>
                                1 grain
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-mountain"
                                    style={{ color: "#c9c9c9" }}
                                ></i>
                                1 ore
                            </li>
                            <li>
                                <i
                                    className="fa-solid fa-cloud"
                                    style={{ color: "#a9d18e" }}
                                ></i>
                                1 wool
                            </li>
                        </ul>

                        <h3>
                            <i className="fa-solid fa-chess-knight"></i>
                            Knight
                        </h3>
                        <p>
                            Activates the robber.
                        </p>
                        <p>
                            If you are the first player to play 3 knight cards,
                            you will earn the Largest Army card.

                            If another playyer plays more knight cards, they will take the
                            Largest Army card.
                        </p>

                        <h3>
                            <i className="fa-solid fa-road"></i>
                            Road Building
                        </h3>
                        <p>
                            Allows you to build 2 roads immediately.
                        </p>

                        <h3>
                            <i className="fa-solid fa-coins"></i>
                            Year of Plenty
                        </h3>
                        <p>
                            Allows you to choose 2 resource cards to draw.
                        </p>

                        <h3>
                            <i className="fa-solid fa-hand-holding-dollar"></i>
                            Monopoly
                        </h3>
                        <p>
                            Forces all players to surrender all of their resources
                            of a type chosen by you.
                        </p>

                        <h3>
                            <i className="fa-solid fa-trophy"></i>
                            Victory Point
                        </h3>
                        <p>
                            Worth 1 Victory Point.
                        </p>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-arrow-right-arrow-left"></i>
                            Trading
                        </h2>
                        <p>
                            Be the first to reach 10 Victory Points.
                            There are 5 ways to earn Victory Points:
                        </p>

                        <h3>
                            <i className="fa-solid fa-money-bill-transfer"></i>
                            Domestic
                        </h3>
                        <p>
                            Domestic trade is between players, and can be initiated on the player's turn.
                            The terms of the trade are decided by the players.
                        </p>

                        <h3>
                            <i className="fa-solid fa-ship"></i>
                            Maritime
                        </h3>
                        <p>
                            Maritime trade exchanges some amount of 1 resource for another resource of
                            the player's choosing.  Martime trade can be conducted at harbours,
                            or during the player's turn.
                        </p>
                        <p>
                            Harbours can offer a 3:1 trade of any resource or 2:1 trade for a specific type of resource.
                            To use a harbour, players must have built a settlement or city adjacent to the harbour.
                            These intersections are highlighted when the harbour is hovered over.
                        </p>
                        <p>
                            A 4:1 trade can also be done during the player's turn through their panel.
                        </p>
                    </section>

                    <section>
                        <h2>
                            <i className="fa-solid fa-user-ninja"></i>
                            Robber
                        </h2>
                        <p>
                            When you roll a number 7 or play a knight card, the robber is activated.
                            When the robber is placed on a tile, that tile will no longer produce
                            resources until the robber is moved away.
                        </p>
                        <ol>
                            <li>
                                All players with more than 7 cards will have to discard half of them
                                (odd numbers round down).
                            </li>
                            <li>
                                The player who activated the robber must move the robber
                                to a different tile.
                            </li>
                            <li>
                                If there are settlements or cities adjacent to the tile that the robber
                                was moved to, the player who activated the robber needs to steal one
                                resource from any of the intersection owners.
                            </li>
                        </ol>
                    </section>

                    <section>
                        <h2 className="rules__link">
                            <a href={rules_pdf} target="blank">
                                <i className="fa-solid fa-link"></i>
                                <span className="tooltip">Official PDF</span>
                                Link to official PDF
                            </a>
                        </h2>
                    </section>
                </div>
            </div>
        </>
    );
}

export default Rules;